name: ecommerce_app
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+5

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.1
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  shimmer: ^3.0.0
  dio: ^5.9.0
  flutter_screenutil: ^5.9.3
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.4
  get_it: ^8.0.1
  carousel_slider_plus: ^7.1.1
  cached_network_image: ^3.4.1
  easy_localization: ^3.0.8
  shared_preferences: ^2.5.3
  go_router: ^16.2.1

dev_dependencies:
  build_runner: ^2.4.15
  json_serializable: ^6.8.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  envied_generator: ^1.1.1
  flutter_lints: ^5.0.0

flutter:


  uses-material-design: true

  assets:
  - assets/images/
  - assets/translations/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
